### ISSUE TITLE
electron在main进程使用lndb，打包后报错 Cannot find module 'lndb'

### ISSUE THREAD

**Issue by seepine** [yansenlei/lndb#4]
**Describe the bug**
electron在main进程使用lndb，打包后报错 Cannot find module 'lndb'

**To Reproduce**
`npm install lndb` ，use in main.js and  `npm run build`

**Expected behavior**
打包后可以正常使用

**Screenshots**
![image](https://user-images.githubusercontent.com/93666053/147843454-337057f4-2b3c-4bfa-bae5-221ea623239a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11

**Comment by RuiKuzk** [comment]
遇到同样的问题。electron 依赖 lndb之后，使用electron-packager去打包，打包之后的.exe文件双击之后提示操作系统不支持
OS：Windows
Version: 10
